DROP TABLE IF EXISTS COUNTRY;

CREATE TABLE COUNTRY (
	ID INT IDENTITY PRIMARY KEY NOT NULL,
	NAME VARCHAR(64) NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);